apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: quarkus-s3
  namespace: s3quarkus
  finalizers:
    - objectbucket.io/finalizer
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: quarkus-s3
  storageClassName: openshift-storage.noobaa.io
